### ISSUE TITLE
Windows install instructions

### ISSUE THREAD

**Issue by adler-j** [comp-imaging/ProxImaL#1]
Currently, when following the installation guide on windows (tested on win 7 and 10) the following error is given:

```
$ conda install numpy scipy pil pip opencv
Fetching package metadata: ....
Error: No packages found in current win-64 channels matching: opencv

You can search for this package on anaconda.org with

    anaconda search -t conda opencv
```

This can be solved (according to [this stackoverflow thread](http://stackoverflow.com/questions/23119413/how-to-install-python-opencv-through-conda)) by running

```
conda install -c https://conda.binstar.org/menpo opencv
```

After doing this, the installation works as expected. This tip may need to be added to the installation instructions.

**Comment by SteveDiamond** [comment]
Thanks! I've added a note for Windows installation.
