### ISSUE TITLE
Cache processed right-hand side for direct least squares solver

### ISSUE THREAD

**Issue by SteveDiamond** [comp-imaging/ProxImaL#12]
We should cache `(K^TK)^{-1}K^Tb` when repeatedly solving  `||Kx - b||^2 + (\rho/2)||x-v||^2` directly.

**Comment by antonysigma** [comment]
Note to self: this can be done with the Halide's cache mechanism:

https://halide-lang.org/docs/class_halide_1_1_func.html#a13f23665f247f820d971a34ad18171fe

The only catch is the need of a "hash" indicating the change of buffer `b` contents. The hash compute overhead may be higher than that of `K_T b`, defeating the purpose.

**Comment by SteveDiamond** [comment]
Nice!
