### ISSUE TITLE
set_ methods should be property setters

### ISSUE THREAD

**Issue by adler-j** [comp-imaging/ProxImaL#14]
There are several instances of `set_some_attribute` in the code, this is considered a Python anti-pattern, see e.g. [this](http://stackoverflow.com/questions/6618002/python-property-versus-getters-and-setters) and [this stackoverflow thread](http://stackoverflow.com/questions/2627002/whats-the-pythonic-way-to-use-getters-and-setters). These should perhaps be changed to either a property + setter pair, e.g. like `Variable.value` currently does it:

``` python
@property
def value(self):
    return self._value

@value.setter
def value(self, val):
    """Assign a value to the variable.
    """
    self._value = val
```

or simply by removing the `set_SOMEVARIABLE` method and setting the attribute as usual: `object.some_attribute = new_value`.

**Comment by antonysigma** [comment]
I did a `git grep "def set_"` in the repo today, and I didn't find any code having the `set_some_attribute` naming pattern. Assuming @adler-j has already submitted the PR to fix it back in 2016.

Closing this thread.
