### ISSUE TITLE
Data folder missing

### ISSUE THREAD

**Issue by adler-j** [comp-imaging/ProxImaL#2]
Several examples seem to be referring a data folder, this is however missing in the repository. See for example [here](https://github.com/comp-imaging/ProxImaL/blob/c92701a5d05a78d433ef4815ccd079b0807fbb95/proximal/examples/test_fft.py#L32).

**Comment by SteveDiamond** [comment]
The data folder is inside the examples directory:
https://github.com/comp-imaging/ProxImaL/tree/master/proximal/examples/data
You must run the example scripts from the examples directory. I added a note in the examples folder that explains this.
