### ISSUE TITLE
Support for several variables

### ISSUE THREAD

**Issue by adler-j** [comp-imaging/ProxImaL#21]
Currently when trying to use several variables at once:

```python
>>> x = proximal.Variable(3)
>>> y = proximal.Variable(6)
>>> rhs = np.array([1, 2, 3])
>>> prob = proximal.Problem([proximal.sum_squares(x - rhs),
                             proximal.sum_squares(proximal.subsample(y, [2]) - x)])
>>> prob.solve()
```

errors are encountered. Is this type of problem intended to be supported in ProxImaL? If not, perhaps a check should be added to disallow it.

**Comment by SteveDiamond** [comment]
Multiple variables are supposed to work. This particular bug is fixed now. A lot of the problem analysis and rewriting is disabled for multiple variables at the moment (though the plan is to make it work).
