### ISSUE TITLE
Extending Lin_Op 

### ISSUE THREAD

**Issue by grauniverse** [comp-imaging/ProxImaL#24]
Hello everyone,

I am currently extending the 'Lin_Op' class by creating a new class 'matrix_nonsquared_mult2'. This operator should perform the following operation:

C * i - h

where:
   - "i" is the variable 442x19800 matrix
   - "h" is some data 442x19800 matrix
   - "C" is  a 442x442 matrix operator
   - "*" denotes a common matrix-matrix multiplication

As can be noted, unlike "mul_elemwise", the dimensions of my objects are all different, so creating this new class by just modifying the forward and adjoint methods of "mul_elemwise" wont be sufficient as some reshaping must be done.

I have defined the constructor so that shapes of both, operator "C" and variable "i" match during the execution of the "forward" method. By the point where the bug occurs, the "adjoint" method hasn't even been referenced yet.

The bug occurs during the execution of the "get_diag" method within my class, during the **"partition/split**" phase. Specifically, in the line:

`self_diag = np.reshape(self.kernel, self.size)`

The reason for the bug is that "self.kernel" contains, well, the 442x442 operator; but "self.size" contains the size of the 442x19800 variable. In the cases of "conv" and "mul_elemwise" modules such conflict never exists: In the first case the kernel is reshaped within the operator's constructor to match the variable size and then the operator acting on the input is a element-wise multiplication; while in the second case, both, kernel and input variable must have same dimensions from the beginning.

At the moment, I can't figure out how to make this to match. I have tried to store different shapes within the constructor of my class but then immediately the program breaks during the "**absorption**" stage at the "forward" method execution, since shapes do not match during the matrix-matrix multiplication. So, where should I do the reshaping and what are the correct shapes/sizes to store?? I think  I don't really understand what is each shape or size for.

I would appreciate any suggestions or ideas. I attach the code below
Thank you in advance.
Javier

`class matrix_nonsquared_mult2(LinOp):

    def __init__(self, kernel, arg, implem = None):
        #assert arg.shape == kernel.shape     #Now we must admit different dimensions
        self.kernel = kernel
        self.forward_kernel = kernel
        shape = arg.shape
        
        super(matrix_nonsquared_mult2, self).__init__([arg], shape, implem)
    
    def init_kernel(self):
        print('Kernel Initialization: matrix_nonsquared_mult2')

    def forward(self, inputs, outputs):
        """The forward operator.

        Reads from inputs and writes to outputs.
        """
        self.forward_kernel
        np.copyto(outputs[0], np.dot(self.kernel,inputs[0])) 

    def adjoint(self, inputs, outputs):
        """The adjoint operator.

        Reads from inputs and writes to outputs.
        """
        print('To be implemented...')
        self.adjoint_kernel = self.forward_kernel.conj()
        

    def is_diag(self, freq=False):

        return not freq and self.input_nodes[0].is_diag(freq)

    def get_diag(self, freq=False):
        """Returns the diagonal representation (A^TA)^(1/2).

        Parameters
        ----------
        freq : bool
            Is the diagonal representation in the frequency domain?
        Returns
        -------
        dict of variable to ndarray
            The diagonal operator acting on each variable.
        """
        assert not freq
        
        var_diags = self.input_nodes[0].get_diag(freq)
        self_diag = np.reshape(self.kernel, self.size)
        for var in var_diags.keys():
            var_diags[var] = var_diags[var]*self_diag
        return var_diags
        

    def norm_bound(self, input_mags):
        """Gives an upper bound on the magnitudes of the outputs given inputs.

        Parameters
        ----------
        input_mags : list
            List of magnitudes of inputs.

        Returns
        -------
        float
            Magnitude of outputs.
        """
        return np.max(np.abs(self.kernel))*input_mags[0]`

**Comment by grauniverse** [comment]
Maybe it could be helpful to provide the function calls traceback from my compiler:

`Traceback (most recent call last):
  File "C:\Users\jgraucho\Desktop\eclipse\plugins\org.python.pydev_5.2.0.201608171824\pysrc\pydevd.py", line 1531, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\jgraucho\Desktop\eclipse\plugins\org.python.pydev_5.2.0.201608171824\pysrc\pydevd.py", line 938, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\jgraucho\workspace\MyFirst\testForTest3run\__init__.py", line 159, in <module>
    prob.solve();
  File "C:\Python27\lib\site-packages\proximal\algorithms\problem.py", line 113, in solve
    self.try_diagonalize)
  File "C:\Python27\lib\site-packages\proximal\algorithms\pock_chambolle.py", line 36, in partition
    x_update = get_least_squares_inverse(quad_ops, b, try_diagonalize)
  File "C:\Python27\lib\site-packages\proximal\algorithms\invert.py", line 77, in get_least_squares_inverse
    diag = stacked.get_diag(freq=False).values()[0]
  File "C:\Python27\lib\site-packages\proximal\lin_ops\vstack.py", line 54, in get_diag
    arg_diags = arg.get_diag(freq)
  File "C:\Python27\lib\site-packages\proximal\lin_ops\scale.py", line 44, in get_diag
    var_diags = self.input_nodes[0].get_diag(freq)
  File "C:\Python27\lib\site-packages\proximal\lin_ops\sum.py", line 48, in get_diag
    arg_diags = arg.get_diag(freq)
  File "C:\Python27\lib\site-packages\proximal\lin_ops\matrix_nonsquared_mult2.py", line 79, in get_diag
    self_diag = np.reshape(self.kernel, self.size)
  File "C:\Python27\lib\site-packages\numpy\core\fromnumeric.py", line 225, in reshape
    return reshape(newshape, order=order)
ValueError: total size of new array must be unchanged`

**Comment by SteveDiamond** [comment]
Delete the ``get_diag`` and ``is_diag`` functions. They're not what you want here. Also the ``norm_bound`` is wrong, so delete that as well.

**Comment by grauniverse** [comment]
Thank you very much Steve. Bug solved.
