### ISSUE TITLE
Variable.__init__ fails with shape given as list

### ISSUE THREAD

**Issue by adler-j** [comp-imaging/ProxImaL#3]
Steps to reproduce:

```python
>>> x = proximal.Variable([2, 2])
TypeError: can only concatenate list (not "tuple") to list
```

**Comment by SteveDiamond** [comment]
I don't get the same error. What version of Python are you using? I made a change that hopefully fixes this bug anyway.

**Comment by adler-j** [comment]
Python 2.7 running on windows 10. I'll see if the updated version still has the fix later today.

**Comment by aringh** [comment]
I don't get the error on my ubuntu 14.04 machine. I installed ProxImaL from git, and the last commit is a843b5be.
```
>>> import proximal
>>> x = proximal.Variable([2, 2])
>>> x
<proximal.lin_ops.variable.Variable object at 0x7f840cbf3450>
```

**Comment by adler-j** [comment]
This now works on my machine as well. Should be closable.
