### ISSUE TITLE
installation instructions need overhaul

### ISSUE THREAD

**Issue by Trass3r** [comp-imaging/ProxImaL#30]
http://www.proximal-lang.org/en/latest/install/index.html
Tested Miniconda3 (Python 3.5) on Win7.
* installation for all users does not work
* misleading dependency conflicts: https://github.com/conda/conda/issues/2791#issuecomment-227618438
* mentioned pil dependency is neither available for python3 nor needed it seems
* opencv install as described did not work
* but was installed automatically with `pip install proximal` just like pillow

It might be better to recommend a normal python installation.

Also I wonder how https://github.com/comp-imaging/ProxImaL/blob/master/continuous_integration/install.sh is supposed to work for 3.5 if miniconda2 is downloaded.

**Comment by Trass3r** [comment]
So in the end this worked to run the sample from the front page.

```
conda install numpy scipy pip
pip install proximal matplotlib
```

**Comment by SteveDiamond** [comment]
Thanks, this is helpful. We haven't been testing python 3 on windows very regularly. What exactly is the difference between miniconda2 and miniconda3? Miniconda2 supports Python 3 environments, it's just python 2 by default.

**Comment by wiedemannc** [comment]
It would be also helpful to include the correct halide version (AFAIK it is the version from April 27th 2016).
