### ISSUE TITLE
Compiler error in fft2_r2c.cpp

### ISSUE THREAD

**Issue by wiedemannc** [comp-imaging/ProxImaL#33]
My compiler (MSVC) complains about WTARGET and HTARGET undeclared identifiers in fft2_r2c.cpp:

```
C:\WinPython\3.5.2.3-64bit-qt5\python-3.5.2.amd64\lib\site-packages\proximal\halide\src\fft2_r2c.cpp(52): error C2065: 'WTARGET': undeclared identifier
C:\WinPython\3.5.2.3-64bit-qt5\python-3.5.2.amd64\lib\site-packages\proximal\halide\src\fft2_r2c.cpp(52): error C2065: 'HTARGET': undeclared identifier
C:\WinPython\3.5.2.3-64bit-qt5\python-3.5.2.amd64\lib\site-packages\proximal\halide\src\fft2_r2c.cpp(56): error C2065: 'WTARGET': undeclared identifier
C:\WinPython\3.5.2.3-64bit-qt5\python-3.5.2.amd64\lib\site-packages\proximal\halide\src\fft2_r2c.cpp(56): error C2065: 'HTARGET': undeclared identifier
```

I didn't find references for these anywhere in the code, so I'm unsure about how to fix these.

**Comment by Trass3r** [comment]
I'm pretty sure I saw it somewhere being passed to the Halide class or similar. But can't find it right now.
Anyway here's the patch I use for compiling the Halide code with msvc in general: https://github.com/Trass3r/ProxImaL/commit/639eeeb97afc4323f353385b4dfb4dbaf3c2ed1d

**Comment by wiedemannc** [comment]
I have used that already - thanks for this :)
