### ISSUE TITLE
Multiple issues with halide.py

### ISSUE THREAD

**Issue by timmeinhardt** [comp-imaging/ProxImaL#44]
While working with _ProxImaL_ in Halide implementation modus I encountered multiple problems in `halide.py`:

1. `e.message` is not correctly transpiled to Python 3. The `message` attribute is not removed even though it does not exist in Python 3 and therefore throws an error. I suggest to remove the `messsage` attribute at all. `"{0}".format(e)` should work in both Python versions.

2. From NumPy >= 1.10.0 the result of [np.isfortran](https://docs.scipy.org/doc/numpy/reference/generated/numpy.isfortran.html) may wary. See the documentation in the link. I therefore suggest to replace `np.isfortran(arg)` with `arg.flags.f_contiguous`.

3. If an error occurs in the `try` statement of the `gengen` function before `header_file` and `object_file` are initialized the function will throw an error in the `finally` statement. I suggest to initialize the two variables like the `launcher_file` before the `try` statement:
```
...
header_file = object_file = launcher_file = '' 
try:
...
```

4. The second compilation commented with _Run generator_ fails on OSX if the correct environment variables aren't set in the subprocess. I therefore added the following lines which are probably not the best solution:
```
        # Run generator
        env = os.environ.copy()
        if sys.platform == "linux" or sys.platform == "linux2":
            cmd = '{0} {1} {2} -e o,h -o {3} {4}'.format(
            generator, generator_flag, function_flag, builddir, target_flags)
        elif sys.platform == "darwin":
            cmd = 'export DYLD_LIBRARY_PATH={5} && {0} {1} {2} -e o,h -o {3} {4}'.format(
            generator, generator_flag, function_flag, builddir, target_flags, env['HALIDE_PATH'] + '/bin/')

        if verbose:
            print('Calling generator')
            print('\t' + cmd)
        subprocess.call(cmd, shell=True)
```

**Comment by ziwenjiang** [comment]
@timmeinhardt hello, when I tried to run the _Run generator_ command, I kept running into the error of `Either -g <name> or -r must be specified; available Generators are: fftR2CImg` after adding the lines you posted. My system is OSX. Can you tell me if you have ever ran into the same error? thanks!

**Comment by timmeinhardt** [comment]
Last time I tried out the code is almost 2 years ago and I can not remember such an error. Unfortunately my changes were net integrated into the repository and therefore might be outdated. Maybe one of the libraries introduced some breaking changes that are not yet considered by changes introduced in this PR.

**Comment by ziwenjiang** [comment]
Indeed. I checked the Halide library and they change a certain amount of syntax and architecture after 2018. Any chance you still have a record of what version of Halide you used at that time, like the commit/branch number? Thanks for the help!

**Comment by timmeinhardt** [comment]
@ziwenjiang Yes, in [this](https://github.com/tum-vision/learn_prox_ops) repository I explain how to run the code and I also specified the Halide version date: 2016/04/27.

Unfortunately the original link to this release is broken. But maybe the date helps you!

**Comment by antonysigma** [comment]
Hi @SteveDiamond I came across your ProxImaL project just a week ago, and I would like to help contribute to the project by porting it to Ubuntu 20.04 + Python 3.6 + Halide 8.0. I wonder if you still accept pull requests?

In the meantime, I managed to get a few of the Halide code to compile again, with around 10% test pass on Travis CI:

https://travis-ci.com/github/antonysigma/ProxImaL/jobs/400369725

**Comment by SteveDiamond** [comment]
Sure, I'm happy to take PRs.

**Comment by antonysigma** [comment]
Thanks. Here you are: https://github.com/comp-imaging/ProxImaL/pull/49
