### ISSUE TITLE
Tests seem to assume Halide is installed

### ISSUE THREAD

**Issue by adler-j** [comp-imaging/ProxImaL#5]
When running the tests without Halide installed several tests fail with messages similar to this:

```
g++.exe: error: ${HALIDE_PATH}/tools/GenGen.cpp: No such file or directory
g++.exe: error: ${HALIDE_PATH}/bin/libHalide.so: No such file or directory
'D:\Programming\ProxImaL\proximal\halide\build\gengen.XXXX' is not recognized as an internal or external command,
operable program or batch file.
Error genererator compilation:
```

Platform used is windows 10 with python 2.7.

**Comment by SteveDiamond** [comment]
I've made it so the tests run properly without halide. I used this to get the tests running on travis CI. I'll add a second integration test with Halide later.
