### ISSUE TITLE
Github Action: Halide-Python binding does not match the Python version specified

### ISSUE THREAD

**Issue by antonysigma** [comp-imaging/ProxImaL#58]
Ok I tried to switch things over to github actions, got pretty far but ran into compilation issues. If you're able to take a look at all I'd really appreciate it!

_Originally posted by @SteveDiamond in https://github.com/comp-imaging/ProxImaL/pull/54#discussion_r602940111_

The problem: Github actions wants to test the ProxImaL project in the non-native Python environment, e.g. v3.7. However, the C++ build system detects the system python (v3.8) and then refuses to link the binaries.

Evidence: https://github.com/comp-imaging/ProxImaL/runs/2214159928#step:6:473

@SteveDiamond Possible solutions:
1. Edit Github action workflows to always use system python (e.g. python 3.6 on Ubuntu 18.04, python 3.8 on Ubuntu 20.04)
2. Edit Meson configuration to always detect the "current" python runtime that the Meson runtime is running on.
Link: https://mesonbuild.com/Python-module.html#find_installation

**Comment by SteveDiamond** [comment]
Thanks for looking into this! I'll look into 1. I don't know much about Meson but I could give 2 a try as well.

**Comment by antonysigma** [comment]
Great! I look forward to it.

In the meantime, I have incorporated solution #2 to the Halide-10 pull request. I am not sure how to execute GH action on the non-default branch though.

https://github.com/comp-imaging/ProxImaL/pull/54/commits/1eab8fc21054eca5aa236ec763b43e1372ca4b96
