### ISSUE TITLE
PEP8 style conformance

### ISSUE THREAD

**Issue by adler-j** [comp-imaging/ProxImaL#8]
I've been looking some at the code now in order to get it working nicely with [ODL](https://github.com/odlgroup/odl), and one thing I've come to notice is that you do not seem to follow the official python style as given in [PEP8](https://www.python.org/dev/peps/pep-0008/). Python differs from most other languages in there being an official style guide that should be used with it, and it is highly recommended to follow it. Further, it is often easier to get started with style conformance early on in the project than waiting until later (trust me, we waited far to long before we did this in ODL).

There are several tools available in order to both check that your code is conforming (such as [pytest pep8](https://pypi.python.org/pypi/pytest-pep8) and the built in pep8 checker for spyder) and also a few that can help you make the code conforming such as [autopep8](https://pypi.python.org/pypi/autopep8) and [autoflakes](https://pypi.python.org/pypi/autoflake/0.6.6).

**Comment by SteveDiamond** [comment]
Wow, I should have been doing this for cvxpy too. I'll fix this in proximal.

**Comment by SteveDiamond** [comment]
Ok, I got a little obsessed with this and now all the code is PEP8 compliant (outside of proximal/examples and proximal/tests).

**Comment by adler-j** [comment]
A tip if you want to keep this up: add `pytest.pep8` to your travis CI build, that way you are forced to do this in each pull request etc :)

**Comment by SteveDiamond** [comment]
Thanks for the tip! I've done this for proximal and also cvxpy now.
